#include<stdio.h>
#include<conio.h>
      void main(void)
      {
       clrscr();
       printf("\tMy Name is Hafiz Mudassir Husain\n");
       printf("\tMy roll no is CSC-22F-145\n");
       printf("\tI am a student of 1st Semester\n");
       printf("\tBatch is Fall-22\n");
       printf("\tdepartment Name is Computer Science\n");
       printf("\tUniversity Name: Sindh Mardarsa-tul-Islam Univertsity\n");
       getch();

      }